/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: AuthorInfo
 * Author: Victor
 * Date: 2023/3/1 17:50
 * Description: 
 * -----------------------------------------------------------------
 */
export class AuthorInfo {
  id: number;
  videoNum: number;
  latestReleaseTime: number;
  icon: string;
  name: string;
  description: string;
}