/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: BannerInfo
 * Author: Victor
 * Date: 2023/3/7 17:42
 * Description: 
 * -----------------------------------------------------------------
 */
 export class BannerInfo {
   background_image: string
   tag_name: string
   link: string
   title: string
   poster_image: string
 }