/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CategoryInfo
 * Author: Victor
 * Date: 2023/3/7 17:20
 * Description: 
 * -----------------------------------------------------------------
 */
export class CategoryInfo {
  id: number
  tagId: number
  defaultAuthorId: number
  name: string
  alias: string
  description: string
  bgPicture: string
  headerImage: string
}