/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: ConsumptionInfo
 * Author: Victor
 * Date: 2023/3/1 18:59
 * Description: 
 * -----------------------------------------------------------------
 */
export class ConsumptionInfo {
  collectionCount: number;
  shareCount: number;
  replyCount: number;
  realCollectionCount: number;
}
 