/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CoverInfo
 * Author: Victor
 * Date: 2023/3/1 17:49
 * Description: 
 * -----------------------------------------------------------------
 */
export class CoverInfo {
  feed: string;
  detail: string;
  blurred: string;
}