import { DailyPagerContentData } from './DailyPagerContentData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: DailyPagerItemContent
 * Author: Victor
 * Date: 2023/3/2 10:25
 * Description: 
 * -----------------------------------------------------------------
 */
 export class DailyPagerItemContent {
  type: string
  trackingData: string
  tag: string
  id: number
  adIndex: number
  data: DailyPagerContentData
 }