import { DailyPagerItemData } from './DailyPagerItemData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: DailyPagerInfo
 * Author: Victor
 * Date: 2023/3/2 10:19
 * Description: 
 * -----------------------------------------------------------------
 */
 export class DailyPagerInfo {
   type: string
   trackingData: string
   tag: string
   id: number
   adIndex: number
   data: DailyPagerItemData
 }