/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: DailyPagerItemHeader
 * Author: Victor
 * Date: 2023/3/2 10:25
 * Description: 
 * -----------------------------------------------------------------
 */
 export class DailyPagerItemHeader {
  id: number
  time: number
  title: string
  font: string
  subTitle: string
  subTitleFont: string
  textAlign: string
  cover: string
  label: string
  actionUrl: string
  icon: string
  iconType: string
  description: string
  showHateVideo: boolean
 }