/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: DiscoveryItemHeader
 * Author: Victor
 * Date: 2023/3/2 11:28
 * Description: 
 * -----------------------------------------------------------------
 */
export class DiscoveryItemHeader {
  id: number
  title: string
  font: string
  textAlign: string
}