import { DiscoveryItemData } from './DiscoveryItemData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: DiscoveryInfo
 * Author: Victor
 * Date: 2023/3/2 11:12
 * Description: 
 * -----------------------------------------------------------------
 */
 export class DiscoveryInfo {
  type: string
  trackingData: string
  tag: string
  id: number
  adIndex: number
  data:DiscoveryItemData
 }