import { DiscoveryCellData } from './DiscoveryCellData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: DiscoveryCellInfo
 * Author: Victor
 * Date: 2023/3/2 11:16
 * Description: 
 * -----------------------------------------------------------------
 */
 export class DiscoveryCellInfo {
   type: string
   trackingData: string
   tag: string
   id: number
   adIndex: number
   data: DiscoveryCellData
 }