/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: DiscoveryCellData
 * Author: Victor
 * Date: 2023/3/2 11:17
 * Description: 
 * -----------------------------------------------------------------
 */
export class DiscoveryCellData {
  id: number
  dataType: string
  title: string
  description: string
  image: string
  actionUrl: string
}