import { FollowItemHeader } from './FollowItemHeader';
import { FollowItemContent } from './FollowItemContent';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: FollowItemData
 * Author: Victor
 * Date: 2023/3/1 17:12
 * Description: 
 * -----------------------------------------------------------------
 */
export class FollowItemData {
  dataType: string;
  header: FollowItemHeader;
  content: FollowItemContent;
}