import { FollowItemData } from './FollowItemData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: FollowInfo
 * Author: Victor
 * Date: 2023/3/1 17:12
 * Description: 
 * -----------------------------------------------------------------
 */
export class FollowInfo {
  type: string;
  trackingData: string;
  tag: string;
  id: number;
  adIndex: number;
  data:FollowItemData;
}