import { FollowItemContentData } from './FollowItemContentData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: FollowItemContent
 * Author: Victor
 * Date: 2023/3/1 17:12
 * Description: 
 * -----------------------------------------------------------------
 */
export class FollowItemContent {
  type: string;
  id: number;
  adIndex: number;
  data:FollowItemContentData;
}