/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: FollowItemHeader
 * Author: Victor
 * Date: 2023/3/1 17:12
 * Description: 
 * -----------------------------------------------------------------
 */
export class FollowItemHeader {
  id: number;
  actionUrl: string;
  icon: string;
  iconType: string;
  issuerName: string;
  time: number;
  showHateVideo: boolean;
}