/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: LightTopicsHeaderInfo
 * Author: Victor
 * Date: 2023/3/8 14:46
 * Description: 
 * -----------------------------------------------------------------
 */
export class LightTopicsHeaderInfo {
  id: number
  time: number
  tagId: number
  actionUrl: string
  icon: string
  iconType: string
  followType: string
  issuerName: string
  showHateVideo: boolean
  topShow: boolean
}