import { LightTopicsContentInfo } from './LightTopicsContentInfo';
import { LightTopicsHeaderInfo } from './LightTopicsHeaderInfo';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: LightTopicsItemData
 * Author: Victor
 * Date: 2023/3/8 14:44
 * Description: 
 * -----------------------------------------------------------------
 */
 export class LightTopicsItemData {
   dataType: string
   header: LightTopicsHeaderInfo
   content: LightTopicsContentInfo
 }