import { LightTopicsContentData } from './LightTopicsContentData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: LightTopicsContentInfo
 * Author: Victor
 * Date: 2023/3/8 14:46
 * Description: 
 * -----------------------------------------------------------------
 */
export class LightTopicsContentInfo {
  type: string
  data:LightTopicsContentData
}