import { LightTopicsItemData } from './LightTopicsItemData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: LightTopicsInfo
 * Author: Victor
 * Date: 2023/3/8 14:43
 * Description: 
 * -----------------------------------------------------------------
 */
export class LightTopicsInfo {
  type: string
  id: number
  adIndex: number
  data: LightTopicsItemData
}