/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: OwnInfo
 * Author: Victor
 * Date: 2023/3/7 18:55
 * Description: 
 * -----------------------------------------------------------------
 */
export class OwnInfo {
  uid: number
  nickname: string
  avatar: string
  ifPgc: boolean
  limitVideoOpen: boolean
  followed: boolean
  expert: boolean
  userType: string
  description: string
  area: string
  gender: string
  registDate: number
  releaseDate: number
  cover: string
  actionUrl: string
}