/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: ShareType
 * Author: Victor
 * Date: 2023/3/8 19:25
 * Description: 
 * -----------------------------------------------------------------
 */
export enum ShareType {
  WECHAT,
  MOMENT,
  QQ,
  QQ_ZONE,
  WEIBO
}