/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: StackStyle
 * Author: Victor
 * Date: 2023/3/30 11:39
 * Description: 
 * -----------------------------------------------------------------
 */
export const StackStyle = {
  IMAGE_Z_INDEX: 2,
  PROGRESS_VALUE: 0,
  PROGRESS_TOTAL: 100,
  PROGRESS_STROKE_WIDTH: 15,
  PROGRESS_SCALE_COUNT: 15,
  PROGRESS_SCALE_WIDTH: 5,
  PROGRESS_Z_INDEX: 1,
  PROGRESS_WIDTH: 80,
  PROGRESS_STEP: 10,
  MILLI_SECONDS: 100
}