import { PgcInfo } from './PgcInfo';
import { UserTabInfo } from './UserTabInfo';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: UserPageData
 * Author: Victor
 * Date: 2023/3/24 15:34
 * Description: 
 * -----------------------------------------------------------------
 */
 export class UserPageData {
   tabInfo: UserTabInfo
   pgcInfo: PgcInfo
 }