import { VideoCellContentData } from './VideoCellContentData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: VideoCellContentInfo
 * Author: Victor
 * Date: 2023/3/3 16:44
 * Description: 
 * -----------------------------------------------------------------
 */
 export class VideoCellContentInfo {
   type: string
   trackingData: string
   tag: string
   id: number
   adIndex: number
   data: VideoCellContentData
 }