/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: VideoCellHeaderInfo
 * Author: Victor
 * Date: 2023/3/3 16:39
 * Description: 
 * -----------------------------------------------------------------
 */
 export class VideoCellHeaderInfo {
   id: number;
   actionUrl: string;
   icon: string;
   iconType: string;
   issuerName: string;
   time: number;
   showHateVideo: boolean;
   title: string
   font: string
   textAlign: string
   subTitle: string
   subTitleFont: string
   cover: string
   label: string
   description: string
 }