import { VideoRelatedItemData } from './VideoRelatedItemData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: VideoRelatedInfo
 * Author: Victor
 * Date: 2023/3/3 16:13
 * Description: 
 * -----------------------------------------------------------------
 */
 export class VideoRelatedInfo {
   type: string
   trackingData: string
   tag: string
   id: number
   adIndex: number
   data: VideoRelatedItemData
 }