import { WeeklyRankingItemData } from './WeeklyRankingItemData';
/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: WeeklyRankingInfo
 * Author: Victor
 * Date: 2023/3/2 16:03
 * Description: 
 * -----------------------------------------------------------------
 */
export class WeeklyRankingInfo {
  type: string
  trackingData: string
  tag: string
  id: number
  adIndex: number
  data: WeeklyRankingItemData
}
