/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: AuthApi
 * Author: Victor
 * Date: 2023/3/2 14:22
 * Description: 
 * -----------------------------------------------------------------
 */

export class AuthApi {
  static readonly USER_INFO = 'https://baobab.kaiyanapp.com/api/v5/userInfo/tab?id='
  static readonly USER_PROFILE = 'https://baobab.kaiyanapp.com/api/v5/userInfo/tab/index?id='
  static readonly USER_VIDEO = 'https://baobab.kaiyanapp.com/api/v4/pgcs/videoList?id='//作品
  static readonly USER_DYNAMICS = 'https://baobab.kaiyanapp.com/api/v5/userInfo/tab/dynamics?id='//动态

  static readonly AUTH = '&udid=d2807c895f0348a180148c9dfa6f2feeac0781b5&deviceModel=hm'
}
