/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: DiscoveryApi
 * Author: Victor
 * Date: 2023/3/2 14:22
 * Description: 
 * -----------------------------------------------------------------
 */

export class DiscoveryApi {
  static readonly DISCOVERY: string = 'http://baobab.kaiyanapp.com/api/v7/index/tab/discovery'
}
