/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: HomeApi
 * Author: Victor
 * Date: 2023/3/1 16:36
 * Description: 
 * -----------------------------------------------------------------
 */

export default class HomeApi {
  static readonly FOLLOW: string = 'http://baobab.kaiyanapp.com/api/v6/community/tab/follow'
  static readonly DAILY_PAPER: string = 'http://baobab.kaiyanapp.com/api/v5/index/tab/feed'
}
