/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: HotApi
 * Author: Victor
 * Date: 2023/3/2 15:55
 * Description: 
 * -----------------------------------------------------------------
 */
export class HotApi {
  static readonly WEEKLY_RANKING = 'http://baobab.kaiyanapp.com/api/v4/rankList/videos?strategy=weekly'
  static readonly MONTHLY_RANKING = 'http://baobab.kaiyanapp.com/api/v4/rankList/videos?strategy=monthly'
  static readonly TOTAL_RANKING = 'http://baobab.kaiyanapp.com/api/v4/rankList/videos?strategy=historical'
}