/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: VideoApi
 * Author: Victor
 * Date: 2023/3/1 16:36
 * Description: 
 * -----------------------------------------------------------------
 */

export class VideoApi {
  static readonly VIDEO_RELATED = 'http://baobab.kaiyanapp.com/api/v4/video/related?id='
}
