/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: Constants
 * Author: Victor
 * Date: 2022/12/8 14:27
 * Description: 
 * -----------------------------------------------------------------
 */

export default class Constants {

  /**
   * Preference saved key.
   */
  static readonly PREFERENCES_KEY_PRIVACY: string = 'isPrivacy';

  /**
   * Preference saved file name.
   */
  static readonly PREFERENCES_FILE_NAME: string = 'myStore';

  /**
   * Launcher page count down.
   */
  static readonly LAUNCHER_DELAY_TIME: number = 1000;

  /**
   * Interval execution time.
   */
  static readonly AD_INTERVAL_TIME: number = 1000;

  /**
   * Width or Height the percentage of the 100.
   */
  static readonly MATCH_PARENT: string = '100%';
  static readonly INTENT_DATA_KEY: string = 'data';

  static readonly USER_SERVICES_AGREEMENT: string = 'https://app.service.hokkj.cn/';
  static readonly PRIVACY_POLICY: string = 'https://app.privacy.hokkj.cn/';

}