/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: RouterPath
 * Author: Victor
 * Date: 2023/3/3 11:55
 * Description: 
 * -----------------------------------------------------------------
 */
export class RouterPath {
  static readonly INDEX_PAGE = 'pages/Index';
  static readonly LAUNCHER_PAGE = 'pages/LauncherPage';
  static readonly AD_PAGE = 'pages/AdPage';
  static readonly SPLASH_PAGE = 'pages/SplashPage';
  static readonly WEB_PAGE = 'pages/WebPage';
  static readonly MAIN_PAGE = 'pages/MainPage';
  static readonly SEARCH_PAGE = 'pages/SearchPage';
  static readonly VIDEO_DETAIL_PAGE = 'pages/VideoDetailPage';
}