/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: PageState
 * Author: Victor
 * Date: 2023/3/17 15:27
 * Description: 
 * -----------------------------------------------------------------
 */
export const enum PageState {
  Loading = 0,
  Success = 1,
  Fail = 2
}