/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: RefreshConstant
 * Author: Victor
 * Date: 2023/3/17 15:27
 * Description: 
 * -----------------------------------------------------------------
 */
export const RefreshConfig = {
  REFRESH_STATE_TAG: 'refresh_state_tag',
  REFRESH_DATA_TAG: 'refresh_data_tag',
  REFRESH_LIST_SCROLL_TOP_TAG: 'refresh_list_scroll_top',

  DELAY_PULL_DOWN_REFRESH: 50,
  CLOSE_PULL_DOWN_REFRESH_TIME: 150,
  DELAY_SHRINK_ANIMATION_TIME: 500,
  CUSTOM_LAYOUT_HEIGHT: 70,
  ANIMATION_DURATION: 500,
  Y_OFF_SET_COEFFICIENT: 0.1,
  DELAY_TIME: 1000,
  DELAY_ANIMATION_DURATION: 300
}