/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: HomeTabModel
 * Author: Victor
 * Date: 2023/2/27 14:53
 * Description: 
 * -----------------------------------------------------------------
 */

export const communityPageTabTitles = [{ id: 0, name: '发现' },{ id: 1, name: '推荐' },{ id: 2, name: '关注' },
  { id: 3, name: '分类' },{ id: 4, name: '专题' }, { id: 5, name: '资讯' }]