/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: HomeTabModel
 * Author: Victor
 * Date: 2023/2/27 14:53
 * Description: 
 * -----------------------------------------------------------------
 */

export interface CategoryInfo {
  id: number;
  defaultAuthorId: number;
  tagId: number;
  name: string;
  alias: string;
  description: string;
  bgPicture: string;
  bgColor: string;
  headerImage: string;
}
