/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: HotTabModel
 * Author: Victor
 * Date: 2023/2/27 14:53
 * Description: 
 * -----------------------------------------------------------------
 */

export const hotPageTabTitles = [{ id: 0, name: '周排行' }, { id: 1, name: '月排行' }, { id: 2, name: '总排行' }]